/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class IntPair {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_IntPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntPair() {
    this(urbiJNI.new_IntPair__SWIG_0(), true);
  }

  public IntPair(int first, int second) {
    this(urbiJNI.new_IntPair__SWIG_1(first, second), true);
  }

  public IntPair(IntPair p) {
    this(urbiJNI.new_IntPair__SWIG_2(IntPair.getCPtr(p), p), true);
  }

  public void setFirst(int value) {
    urbiJNI.IntPair_first_set(swigCPtr, this, value);
  }

  public int getFirst() {
    return urbiJNI.IntPair_first_get(swigCPtr, this);
  }

  public void setSecond(int value) {
    urbiJNI.IntPair_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return urbiJNI.IntPair_second_get(swigCPtr, this);
  }

}
