/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public enum LockMode {
  LOCK_NONE,
  LOCK_FUNCTION,
  LOCK_INSTANCE,
  LOCK_CLASS,
  LOCK_MODULE;

  public final int swigValue() {
    return swigValue;
  }

  public static LockMode swigToEnum(int swigValue) {
    LockMode[] swigValues = LockMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (LockMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + LockMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private LockMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private LockMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private LockMode(LockMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

