/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class SWIGTYPE_p_libport__ThreadPool__rTaskLock {
  private long swigCPtr;

  protected SWIGTYPE_p_libport__ThreadPool__rTaskLock(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_libport__ThreadPool__rTaskLock() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_libport__ThreadPool__rTaskLock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

