/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class SWIGTYPE_p_urbi__UList__list_type__iterator {
  private long swigCPtr;

  protected SWIGTYPE_p_urbi__UList__list_type__iterator(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_urbi__UList__list_type__iterator() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_urbi__UList__list_type__iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

