/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class TimerHandle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TimerHandle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TimerHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_TimerHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static TimerHandle create(String s) {
    return new TimerHandle(urbiJNI.TimerHandle_create(s), true);
  }

  public String get() {
    return urbiJNI.TimerHandle_get(swigCPtr, this);
  }

  public TimerHandle() {
    this(urbiJNI.new_TimerHandle(), true);
  }

}
