/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public enum UBinaryType {
  BINARY_NONE,
  BINARY_UNKNOWN,
  BINARY_IMAGE,
  BINARY_SOUND;

  public final int swigValue() {
    return swigValue;
  }

  public static UBinaryType swigToEnum(int swigValue) {
    UBinaryType[] swigValues = UBinaryType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (UBinaryType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + UBinaryType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private UBinaryType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private UBinaryType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private UBinaryType(UBinaryType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

