/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;
  /// Binary data of known or unknown type.
  ///
  /// Handles its memory: the data field will be freed when the
  /// destructor is called.

public class UBinary {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UBinary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UBinary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UBinary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

      /// Deep copy constructor.
 public  UBinary() {
    this(urbiJNI.new_UBinary__SWIG_0(), true);
  }

      /// Deep copy constructor.
 public  UBinary(UBinary b, boolean copy, boolean temp) {
    this(urbiJNI.new_UBinary__SWIG_1(UBinary.getCPtr(b), b, copy, temp), true);
  }

      /// Deep copy constructor.
 public  UBinary(UBinary b, boolean copy) {
    this(urbiJNI.new_UBinary__SWIG_2(UBinary.getCPtr(b), b, copy), true);
  }

      /// Deep copy constructor.
 public  UBinary(UBinary b) {
    this(urbiJNI.new_UBinary__SWIG_3(UBinary.getCPtr(b), b), true);
  }

      /// Deep copy constructor.
 public  UBinary(UImage arg0, boolean copy) {
    this(urbiJNI.new_UBinary__SWIG_4(UImage.getCPtr(arg0), arg0, copy), true);
  }

      /// Deep copy constructor.
 public  UBinary(UImage arg0) {
    this(urbiJNI.new_UBinary__SWIG_5(UImage.getCPtr(arg0), arg0), true);
  }

      /// Deep copy constructor.
 public  UBinary(USound arg0, boolean copy) {
    this(urbiJNI.new_UBinary__SWIG_6(USound.getCPtr(arg0), arg0, copy), true);
  }

      /// Deep copy constructor.
 public  UBinary(USound arg0) {
    this(urbiJNI.new_UBinary__SWIG_7(USound.getCPtr(arg0), arg0), true);
  }

      /// Deep copy.
 public  UBinary setValue(UBinary b) {
    return new UBinary(urbiJNI.UBinary_setValue(swigCPtr, this, UBinary.getCPtr(b), b), false);
  }

      /// Store the result of getMessage() in member \a message.
 public  void buildMessage() {
    urbiJNI.UBinary_buildMessage(swigCPtr, this);
  }

      /// Get header.
 public  String getMessage() {
    return urbiJNI.UBinary_getMessage(swigCPtr, this);
  }

      /// Clear all the buffers that were allocated by the system.
 public  void clear() {
    urbiJNI.UBinary_clear(swigCPtr, this);
  }

  public void setType(UBinaryType value) {
    urbiJNI.UBinary_type_set(swigCPtr, this, value.swigValue());
  }

  public UBinaryType getType() {
    return UBinaryType.swigToEnum(urbiJNI.UBinary_type_get(swigCPtr, this));
  }

  public void setAllocated_(boolean value) {
    urbiJNI.UBinary_allocated__set(swigCPtr, this, value);
  }

  public boolean getAllocated_() {
    return urbiJNI.UBinary_allocated__get(swigCPtr, this);
  }

  public void setTemporary_(boolean value) {
    urbiJNI.UBinary_temporary__set(swigCPtr, this, value);
  }

  public boolean getTemporary_() {
    return urbiJNI.UBinary_temporary__get(swigCPtr, this);
  }

  public UImage uimageValue() {
    return new UImage(urbiJNI.UBinary_uimageValue(swigCPtr, this), true);
  }

  public USound usoundValue() {
    return new USound(urbiJNI.UBinary_usoundValue(swigCPtr, this), true);
  }

  public long getSize() {
    return urbiJNI.UBinary_getSize(swigCPtr, this);
  }

  public String getExtraHeader() {
    return urbiJNI.UBinary_getExtraHeader(swigCPtr, this);
  }

  public void setExtraHeader(String msg) {
    urbiJNI.UBinary_setExtraHeader(swigCPtr, this, msg);
  }

  public void setData(byte[] value) {
    urbiJNI.UBinary_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
  return urbiJNI.UBinary_data_get(swigCPtr, this);
}

}
