/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UContextImpl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UContextImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UContextImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UContextImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

        /// Inject all loaded uobjects in the system by calling newUObjectClass.
 public  void init() {
    urbiJNI.UContextImpl_init(swigCPtr, this);
  }

        /// Inject a specific uobject
 public  boolean bind(String name, String rename) {
    return urbiJNI.UContextImpl_bind__SWIG_0(swigCPtr, this, name, rename);
  }

        /// Inject a specific uobject
 public  boolean bind(String name) {
    return urbiJNI.UContextImpl_bind__SWIG_1(swigCPtr, this, name);
  }

        /// Called to instanciate the first Object of class.
 public  void newUObjectClass(baseURBIStarter s) {
    urbiJNI.UContextImpl_newUObjectClass(swigCPtr, this, baseURBIStarter.getCPtr(s), s);
  }

  public void newUObjectHubClass(baseURBIStarterHub s) {
    urbiJNI.UContextImpl_newUObjectHubClass(swigCPtr, this, baseURBIStarterHub.getCPtr(s), s);
  }

        /// Retrieve a UObjectHub based on its name or return 0 if not found.
 public  UObjectHub getUObjectHub(String n) {
    long cPtr = urbiJNI.UContextImpl_getUObjectHub(swigCPtr, this, n);
    return (cPtr == 0) ? null : new UObjectHub(cPtr, false);
  }

        /// Retrieve a UObject based on its name or return 0 if not found.
 public  UObjectCPP getUObject(String n) {
    long cPtr = urbiJNI.UContextImpl_getUObject(swigCPtr, this, n);
    return (cPtr == 0) ? null : new UObjectCPP(cPtr, false);
  }

        /// Send Urbi code (ghost connection in plugin mode, default
      /// connection in remote mode).
 public  void uobject_unarmorAndSend(String str) {
    urbiJNI.UContextImpl_uobject_unarmorAndSend(swigCPtr, this, str);
  }

        /// Send buf to the connection hosting the UObject.
 public  void send(String str) {
    urbiJNI.UContextImpl_send__SWIG_0(swigCPtr, this, str);
  }

  public void call(String object, String method, SWIGTYPE_p_UAutoValue v1, SWIGTYPE_p_UAutoValue v2, SWIGTYPE_p_UAutoValue v3, SWIGTYPE_p_UAutoValue v4, SWIGTYPE_p_UAutoValue v5, SWIGTYPE_p_UAutoValue v6) {
    urbiJNI.UContextImpl_call__SWIG_0(swigCPtr, this, object, method, SWIGTYPE_p_UAutoValue.getCPtr(v1), SWIGTYPE_p_UAutoValue.getCPtr(v2), SWIGTYPE_p_UAutoValue.getCPtr(v3), SWIGTYPE_p_UAutoValue.getCPtr(v4), SWIGTYPE_p_UAutoValue.getCPtr(v5), SWIGTYPE_p_UAutoValue.getCPtr(v6));
  }

  public void call(String object, String method, SWIGTYPE_p_UAutoValue v1, SWIGTYPE_p_UAutoValue v2, SWIGTYPE_p_UAutoValue v3, SWIGTYPE_p_UAutoValue v4, SWIGTYPE_p_UAutoValue v5) {
    urbiJNI.UContextImpl_call__SWIG_1(swigCPtr, this, object, method, SWIGTYPE_p_UAutoValue.getCPtr(v1), SWIGTYPE_p_UAutoValue.getCPtr(v2), SWIGTYPE_p_UAutoValue.getCPtr(v3), SWIGTYPE_p_UAutoValue.getCPtr(v4), SWIGTYPE_p_UAutoValue.getCPtr(v5));
  }

  public void call(String object, String method, SWIGTYPE_p_UAutoValue v1, SWIGTYPE_p_UAutoValue v2, SWIGTYPE_p_UAutoValue v3, SWIGTYPE_p_UAutoValue v4) {
    urbiJNI.UContextImpl_call__SWIG_2(swigCPtr, this, object, method, SWIGTYPE_p_UAutoValue.getCPtr(v1), SWIGTYPE_p_UAutoValue.getCPtr(v2), SWIGTYPE_p_UAutoValue.getCPtr(v3), SWIGTYPE_p_UAutoValue.getCPtr(v4));
  }

  public void call(String object, String method, SWIGTYPE_p_UAutoValue v1, SWIGTYPE_p_UAutoValue v2, SWIGTYPE_p_UAutoValue v3) {
    urbiJNI.UContextImpl_call__SWIG_3(swigCPtr, this, object, method, SWIGTYPE_p_UAutoValue.getCPtr(v1), SWIGTYPE_p_UAutoValue.getCPtr(v2), SWIGTYPE_p_UAutoValue.getCPtr(v3));
  }

  public void call(String object, String method, SWIGTYPE_p_UAutoValue v1, SWIGTYPE_p_UAutoValue v2) {
    urbiJNI.UContextImpl_call__SWIG_4(swigCPtr, this, object, method, SWIGTYPE_p_UAutoValue.getCPtr(v1), SWIGTYPE_p_UAutoValue.getCPtr(v2));
  }

  public void call(String object, String method, SWIGTYPE_p_UAutoValue v1) {
    urbiJNI.UContextImpl_call__SWIG_5(swigCPtr, this, object, method, SWIGTYPE_p_UAutoValue.getCPtr(v1));
  }

  public void call(String object, String method) {
    urbiJNI.UContextImpl_call__SWIG_6(swigCPtr, this, object, method);
  }

  public void declare_event(UEvent owner) {
    urbiJNI.UContextImpl_declare_event(swigCPtr, this, UEvent.getCPtr(owner), owner);
  }

  public void emit(String object, SWIGTYPE_p_UAutoValue v1, SWIGTYPE_p_UAutoValue v2, SWIGTYPE_p_UAutoValue v3, SWIGTYPE_p_UAutoValue v4, SWIGTYPE_p_UAutoValue v5, SWIGTYPE_p_UAutoValue v6, SWIGTYPE_p_UAutoValue v7) {
    urbiJNI.UContextImpl_emit(swigCPtr, this, object, SWIGTYPE_p_UAutoValue.getCPtr(v1), SWIGTYPE_p_UAutoValue.getCPtr(v2), SWIGTYPE_p_UAutoValue.getCPtr(v3), SWIGTYPE_p_UAutoValue.getCPtr(v4), SWIGTYPE_p_UAutoValue.getCPtr(v5), SWIGTYPE_p_UAutoValue.getCPtr(v6), SWIGTYPE_p_UAutoValue.getCPtr(v7));
  }

        /// Return the mode in which the code is running.
 public  SWIGTYPE_p_UObjectMode getRunningMode() {
    return new SWIGTYPE_p_UObjectMode(urbiJNI.UContextImpl_getRunningMode(swigCPtr, this), true);
  }

        /// Get the kernel major,minor version
 public  IntPair kernelVersion() {
    return new IntPair(urbiJNI.UContextImpl_kernelVersion(swigCPtr, this), true);
  }

        /// Yield execution until next cycle.
      /// Process pending messages in remote mode.
 public  void yield() {
    urbiJNI.UContextImpl_yield(swigCPtr, this);
  }

        /// Yield execution until \b deadline is met (see libport::utime()).
 public  void yield_until(long deadline) {
    urbiJNI.UContextImpl_yield_until(swigCPtr, this, deadline);
  }

        /// Yield execution for \b delay.
      /// Bounces to yield_until.
 public  void yield_for(long delay) {
    urbiJNI.UContextImpl_yield_for(swigCPtr, this, delay);
  }

        /** Yield execution until something else is scheduled,
       *  or until a message is received in remote mode.
       */
 public  void yield_until_things_changed() {
    urbiJNI.UContextImpl_yield_until_things_changed(swigCPtr, this);
  }

        /** If \b s is true, mark the current task as having no side effect.
       * This call has no effect in remote mode.
       */
 public  void side_effect_free_set(boolean s) {
    urbiJNI.UContextImpl_side_effect_free_set(swigCPtr, this, s);
  }

        /// Get the current side_effect_free state.
 public  boolean side_effect_free_get() {
    return urbiJNI.UContextImpl_side_effect_free_get(swigCPtr, this);
  }

  public UVarImpl getVarImpl() {
    long cPtr = urbiJNI.UContextImpl_getVarImpl(swigCPtr, this);
    return (cPtr == 0) ? null : new UVarImpl(cPtr, false);
  }

  public UObjectImpl getObjectImpl() {
    long cPtr = urbiJNI.UContextImpl_getObjectImpl(swigCPtr, this);
    return (cPtr == 0) ? null : new UObjectImpl(cPtr, false);
  }

        /// Default implementations appends to 'objects'.
 public  void registerObject(UObjectCPP o) {
    urbiJNI.UContextImpl_registerObject(swigCPtr, this, UObjectCPP.getCPtr(o), o);
  }

  public void registerHub(UObjectHub arg0) {
    urbiJNI.UContextImpl_registerHub(swigCPtr, this, UObjectHub.getCPtr(arg0), arg0);
  }

  public void removeHub(UObjectHub arg0) {
    urbiJNI.UContextImpl_removeHub(swigCPtr, this, UObjectHub.getCPtr(arg0), arg0);
  }

  public void setHubUpdate(UObjectHub arg0, double arg1) {
    urbiJNI.UContextImpl_setHubUpdate(swigCPtr, this, UObjectHub.getCPtr(arg0), arg0, arg1);
  }

        /// Called by the urbiStarter after each UObject instanciation.
 public  void instanciated(UObjectCPP arg0) {
    urbiJNI.UContextImpl_instanciated(swigCPtr, this, UObjectCPP.getCPtr(arg0), arg0);
  }

  public void addCleanup(SWIGTYPE_p_boost__function0T_void_t op) {
    urbiJNI.UContextImpl_addCleanup(swigCPtr, this, SWIGTYPE_p_boost__function0T_void_t.getCPtr(op));
  }

  public void pushCleanupStack() {
    urbiJNI.UContextImpl_pushCleanupStack(swigCPtr, this);
  }

  public void popCleanupStack() {
    urbiJNI.UContextImpl_popCleanupStack(swigCPtr, this);
  }

  public void lock() {
    urbiJNI.UContextImpl_lock(swigCPtr, this);
  }

  public void unlock() {
    urbiJNI.UContextImpl_unlock(swigCPtr, this);
  }

  public void setRtpSend(SWIGTYPE_p_f_p_urbi__UObject_r_q_const__urbi__UValue__void value) {
    urbiJNI.UContextImpl_rtpSend_set(swigCPtr, this, SWIGTYPE_p_f_p_urbi__UObject_r_q_const__urbi__UValue__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_urbi__UObject_r_q_const__urbi__UValue__void getRtpSend() {
    long cPtr = urbiJNI.UContextImpl_rtpSend_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_urbi__UObject_r_q_const__urbi__UValue__void(cPtr, false);
  }

  public void setRtpSendGrouped(SWIGTYPE_p_f_p_urbi__UObject_r_q_const__std__string_r_q_const__urbi__UValue_long_long__void value) {
    urbiJNI.UContextImpl_rtpSendGrouped_set(swigCPtr, this, SWIGTYPE_p_f_p_urbi__UObject_r_q_const__std__string_r_q_const__urbi__UValue_long_long__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_urbi__UObject_r_q_const__std__string_r_q_const__urbi__UValue_long_long__void getRtpSendGrouped() {
    long cPtr = urbiJNI.UContextImpl_rtpSendGrouped_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_urbi__UObject_r_q_const__std__string_r_q_const__urbi__UValue_long_long__void(cPtr, false);
  }

}
