/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public enum UDataType {
  DATA_BINARY(0),
  DATA_DICTIONARY(1),
  DATA_DOUBLE(2),
  DATA_LIST(3),
  DATA_STRING(5),
  DATA_SLOTNAME(6),
  DATA_VOID(7);

  public final int swigValue() {
    return swigValue;
  }

  public static UDataType swigToEnum(int swigValue) {
    UDataType[] swigValues = UDataType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (UDataType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + UDataType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private UDataType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private UDataType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private UDataType(UDataType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

