/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UDictionaryCPPIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UDictionaryCPPIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UDictionaryCPPIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UDictionaryCPPIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UDictionaryCPPIterator(UDictionary map) {
    this(urbiJNI.new_UDictionaryCPPIterator(UDictionary.getCPtr(map), map), true);
  }

  public void next() {
    urbiJNI.UDictionaryCPPIterator_next(swigCPtr, this);
  }

  public boolean hasNext() {
    return urbiJNI.UDictionaryCPPIterator_hasNext(swigCPtr, this);
  }

  public String getKey() {
    return urbiJNI.UDictionaryCPPIterator_getKey(swigCPtr, this);
  }

  public UValue getValue() {
    return new UValue(urbiJNI.UDictionaryCPPIterator_getValue(swigCPtr, this), true);
  }

}
