/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UImageImpl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UImageImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UImageImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UImageImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static UImageImpl make() {
    return new UImageImpl(urbiJNI.UImageImpl_make(), true);
  }

  public void init() {
    urbiJNI.UImageImpl_init(swigCPtr, this);
  }

  public String format_string() {
    return urbiJNI.UImageImpl_format_string(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream dump(SWIGTYPE_p_std__ostream o) {
    return new SWIGTYPE_p_std__ostream(urbiJNI.UImageImpl_dump(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(o)), false);
  }

  public void setData(byte[] value) {
    urbiJNI.UImageImpl_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
  return urbiJNI.UImageImpl_data_get(swigCPtr, this);
}

  public void setSize(long value) {
    urbiJNI.UImageImpl_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return urbiJNI.UImageImpl_size_get(swigCPtr, this);
  }

  public void setWidth(long value) {
    urbiJNI.UImageImpl_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return urbiJNI.UImageImpl_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    urbiJNI.UImageImpl_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return urbiJNI.UImageImpl_height_get(swigCPtr, this);
  }

  public void setImageFormat(UImageFormat value) {
    urbiJNI.UImageImpl_imageFormat_set(swigCPtr, this, value.swigValue());
  }

  public UImageFormat getImageFormat() {
    return UImageFormat.swigToEnum(urbiJNI.UImageImpl_imageFormat_get(swigCPtr, this));
  }

  public void deleteData() {
    urbiJNI.UImageImpl_deleteData(swigCPtr, this);
  }

  public UImageImpl() {
    this(urbiJNI.new_UImageImpl(), true);
  }

}
