/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;
  /*---------.
  | UImage.  |
  `---------*/
  /** Class encapsulating an image.

   This class does not handle its memory: the data field msut be
   freed manualy.  */

public class UImage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UImage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UImage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

      /// Return an empty UImage.
    /// Not a constructor so that we can still put it in a union.
 public  static UImage make() {
    return new UImage(urbiJNI.UImage_make(), true);
  }

  public void init() {
    urbiJNI.UImage_init(swigCPtr, this);
  }

      /// Return a legible definition of imageFormat.
 public  String format_string() {
    return urbiJNI.UImage_format_string(swigCPtr, this);
  }

  public void setData(byte[] value) {
    urbiJNI.UImage_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
  return urbiJNI.UImage_data_get(swigCPtr, this);
}

  public void setSize(long value) {
    urbiJNI.UImage_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return urbiJNI.UImage_size_get(swigCPtr, this);
  }

  public void setWidth(long value) {
    urbiJNI.UImage_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return urbiJNI.UImage_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    urbiJNI.UImage_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return urbiJNI.UImage_height_get(swigCPtr, this);
  }

  public void setImageFormat(UImageFormat value) {
    urbiJNI.UImage_imageFormat_set(swigCPtr, this, value.swigValue());
  }

  public UImageFormat getImageFormat() {
    return UImageFormat.swigToEnum(urbiJNI.UImage_imageFormat_get(swigCPtr, this));
  }

  public void deleteData() {
    urbiJNI.UImage_deleteData(swigCPtr, this);
  }

  public UImage() {
    this(urbiJNI.new_UImage(), true);
  }

}
