/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public enum UImageFormat {
  IMAGE_UNKNOWN(0),
  IMAGE_RGB(1),
  IMAGE_YCbCr(2),
  IMAGE_YUV(2),
  IMAGE_JPEG(3),
  IMAGE_PPM(4),
  IMAGE_YUV422(5),
  IMAGE_GREY8(6),
  IMAGE_GREY4(7),
  IMAGE_YUV411_PLANAR(8),
  IMAGE_NV12(9),
  IMAGE_YUV420_PLANAR(10);

  public final int swigValue() {
    return swigValue;
  }

  public static UImageFormat swigToEnum(int swigValue) {
    UImageFormat[] swigValues = UImageFormat.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (UImageFormat swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + UImageFormat.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private UImageFormat() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private UImageFormat(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private UImageFormat(UImageFormat swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

