/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;
  /*--------.
  | UList.  |
  `--------*/
  /// Class storing URBI List type

public class UList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UList() {
    this(urbiJNI.new_UList__SWIG_0(), true);
  }

  public UList(UList b) {
    this(urbiJNI.new_UList__SWIG_1(UList.getCPtr(b), b), true);
  }

  public UList setValue(UList b) {
    return new UList(urbiJNI.UList_setValue__SWIG_0(swigCPtr, this, UList.getCPtr(b), b), false);
  }

  public UList setValue(UVar v) {
    return new UList(urbiJNI.UList_setValue__SWIG_2(swigCPtr, this, UVar.getCPtr(v), v), false);
  }

  public SWIGTYPE_p_urbi__UList__list_type__iterator begin() {
    return new SWIGTYPE_p_urbi__UList__list_type__iterator(urbiJNI.UList_begin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_urbi__UList__list_type__iterator end() {
    return new SWIGTYPE_p_urbi__UList__list_type__iterator(urbiJNI.UList_end__SWIG_0(swigCPtr, this), true);
  }

  public void pop_back() {
    urbiJNI.UList_pop_back(swigCPtr, this);
  }

  public UValue front() {
    return new UValue(urbiJNI.UList_front(swigCPtr, this), false);
  }

  public UValue get(long i) {
    return new UValue(urbiJNI.UList_get__SWIG_0(swigCPtr, this, i), false);
  }

  public long size() {
    return urbiJNI.UList_size(swigCPtr, this);
  }

  public void setOffset(long n) {
    urbiJNI.UList_setOffset(swigCPtr, this, n);
  }

  public void setArray(UValueVector value) {
    urbiJNI.UList_array_set(swigCPtr, this, UValueVector.getCPtr(value), value);
  }

  public UValueVector getArray() {
    long cPtr = urbiJNI.UList_array_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UValueVector(cPtr, false);
  }

  public UList push_back(UValue v) {
    return new UList(urbiJNI.UList_push_back__SWIG_1(swigCPtr, this, UValue.getCPtr(v), v), false);
  }

  public UList push_back(UList v) {
    return new UList(urbiJNI.UList_push_back__SWIG_2(swigCPtr, this, UList.getCPtr(v), v), false);
  }

  public UList push_back(UBinary v) {
    return new UList(urbiJNI.UList_push_back__SWIG_3(swigCPtr, this, UBinary.getCPtr(v), v), false);
  }

  public UList push_back(USound v) {
    return new UList(urbiJNI.UList_push_back__SWIG_4(swigCPtr, this, USound.getCPtr(v), v), false);
  }

  public UList push_back(UImage v) {
    return new UList(urbiJNI.UList_push_back__SWIG_5(swigCPtr, this, UImage.getCPtr(v), v), false);
  }

  public UList push_back(String v) {
    return new UList(urbiJNI.UList_push_back__SWIG_6(swigCPtr, this, v), false);
  }

  public UList push_back(int v) {
    return new UList(urbiJNI.UList_push_back__SWIG_7(swigCPtr, this, v), false);
  }

  public UList push_back(long v) {
    return new UList(urbiJNI.UList_push_back__SWIG_8(swigCPtr, this, v), false);
  }

  public UList push_back(double v) {
    return new UList(urbiJNI.UList_push_back__SWIG_9(swigCPtr, this, v), false);
  }

  public UList push_back(float v) {
    return new UList(urbiJNI.UList_push_back__SWIG_10(swigCPtr, this, v), false);
  }

  public UList push_back(char v) {
    return new UList(urbiJNI.UList_push_back__SWIG_11(swigCPtr, this, v), false);
  }

  public UList push_back(boolean v) {
    return new UList(urbiJNI.UList_push_back__SWIG_12(swigCPtr, this, v), false);
  }

  public String toString() {
    return urbiJNI.UList_toString(swigCPtr, this);
  }

}
