/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;
  /// Class containing all informations related to an URBI message.

public class UMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UMessage(UAbstractClient client) {
    this(urbiJNI.new_UMessage__SWIG_0(UAbstractClient.getCPtr(client), client), true);
  }

  public UMessage(UAbstractClient client, int timestamp, String tag, String message) {
    this(urbiJNI.new_UMessage__SWIG_1(UAbstractClient.getCPtr(client), client, timestamp, tag, message), true);
  }

  public UMessage(UAbstractClient client, int timestamp, String tag, String message, SWIGTYPE_p_std__listT_urbi__BinaryData_t bins) {
    this(urbiJNI.new_UMessage__SWIG_2(UAbstractClient.getCPtr(client), client, timestamp, tag, message, SWIGTYPE_p_std__listT_urbi__BinaryData_t.getCPtr(bins)), true);
  }

  public UMessage(UMessage source) {
    this(urbiJNI.new_UMessage__SWIG_4(UMessage.getCPtr(source), source), true);
  }

  public void setTimestamp(int value) {
    urbiJNI.UMessage_timestamp_set(swigCPtr, this, value);
  }

  public int getTimestamp() {
    return urbiJNI.UMessage_timestamp_get(swigCPtr, this);
  }

  public void setTag(String value) {
    urbiJNI.UMessage_tag_set(swigCPtr, this, value);
  }

  public String getTag() {
    return urbiJNI.UMessage_tag_get(swigCPtr, this);
  }

  public void setType(UMessageType value) {
    urbiJNI.UMessage_type_set(swigCPtr, this, value.swigValue());
  }

  public UMessageType getType() {
    return UMessageType.swigToEnum(urbiJNI.UMessage_type_get(swigCPtr, this));
  }

  public void setValue(UValue value) {
    urbiJNI.UMessage_value_set(swigCPtr, this, UValue.getCPtr(value), value);
  }

  public UValue getValue() {
    long cPtr = urbiJNI.UMessage_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UValue(cPtr, false);
  }

  public void setMessage(String value) {
    urbiJNI.UMessage_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return urbiJNI.UMessage_message_get(swigCPtr, this);
  }

  public void setRawMessage(String value) {
    urbiJNI.UMessage_rawMessage_set(swigCPtr, this, value);
  }

  public String getRawMessage() {
    return urbiJNI.UMessage_rawMessage_get(swigCPtr, this);
  }

  public UAbstractClient getClient() {
    return new UAbstractClient(urbiJNI.UMessage_getClient(swigCPtr, this), false);
  }

}
