/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public enum UMessageType {
  MESSAGE_SYSTEM,
  MESSAGE_ERROR,
  MESSAGE_DATA;

  public final int swigValue() {
    return swigValue;
  }

  public static UMessageType swigToEnum(int swigValue) {
    UMessageType[] swigValues = UMessageType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (UMessageType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + UMessageType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private UMessageType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private UMessageType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private UMessageType(UMessageType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

