/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UNamedValueVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UNamedValueVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UNamedValueVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UNamedValueVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UNamedValueVector() {
    this(urbiJNI.new_UNamedValueVector__SWIG_0(), true);
  }

  public UNamedValueVector(long n) {
    this(urbiJNI.new_UNamedValueVector__SWIG_1(n), true);
  }

  public long size() {
    return urbiJNI.UNamedValueVector_size(swigCPtr, this);
  }

  public long capacity() {
    return urbiJNI.UNamedValueVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    urbiJNI.UNamedValueVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return urbiJNI.UNamedValueVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    urbiJNI.UNamedValueVector_clear(swigCPtr, this);
  }

  public void add(UNamedValue x) {
    urbiJNI.UNamedValueVector_add(swigCPtr, this, UNamedValue.getCPtr(x), x);
  }

  public UNamedValue get(int i) {
    return new UNamedValue(urbiJNI.UNamedValueVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, UNamedValue val) {
    urbiJNI.UNamedValueVector_set(swigCPtr, this, i, UNamedValue.getCPtr(val), val);
  }

}
