/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UObjectImpl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UObjectImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UObjectImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UObjectImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

        // Called by uobject constructor
 public  void initialize(UObjectCPP owner) {
    urbiJNI.UObjectImpl_initialize(swigCPtr, this, UObjectCPP.getCPtr(owner), owner);
  }

  public void clean() {
    urbiJNI.UObjectImpl_clean(swigCPtr, this);
  }

  public void setUpdate(double period) {
    urbiJNI.UObjectImpl_setUpdate(swigCPtr, this, period);
  }

  public boolean removeTimer(TimerHandle h) {
    return urbiJNI.UObjectImpl_removeTimer(swigCPtr, this, TimerHandle.getCPtr(h), h);
  }

}
