/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class URBIStarterJAVA extends baseURBIStarter {
  private long swigCPtr;

  protected URBIStarterJAVA(long cPtr, boolean cMemoryOwn) {
    super(urbiJNI.SWIGURBIStarterJAVAUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(URBIStarterJAVA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_URBIStarterJAVA(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    urbiJNI.URBIStarterJAVA_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    urbiJNI.URBIStarterJAVA_change_ownership(this, swigCPtr, true);
  }

  public URBIStarterJAVA(String name, boolean local) {
    this(urbiJNI.new_URBIStarterJAVA__SWIG_0(name, local), true);
    urbiJNI.URBIStarterJAVA_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public URBIStarterJAVA(String name) {
    this(urbiJNI.new_URBIStarterJAVA__SWIG_1(name), true);
    urbiJNI.URBIStarterJAVA_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public UObjectCPP instanciate(UContextImpl ctx, String n) {
    long cPtr = (getClass() == URBIStarterJAVA.class) ? urbiJNI.URBIStarterJAVA_instanciate(swigCPtr, this, UContextImpl.getCPtr(ctx), ctx, n) : urbiJNI.URBIStarterJAVA_instanciateSwigExplicitURBIStarterJAVA(swigCPtr, this, UContextImpl.getCPtr(ctx), ctx, n);
    return (cPtr == 0) ? null : new UObjectCPP(cPtr, false);
  }

}
