/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public interface urbiConstants {
  public final static String __SRCDIR__ = "\0";
  public final static int URBI_MAX_TAG_LENGTH = 64;

  public final static int UINVALIDCALLBACKID = 0;
  public final static int USE_VOID = 1;
  public final static int URBI_UOBJECT_VERSION = 2;
}
