/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public enum USoundFormat {
  SOUND_RAW(0),
  SOUND_WAV(1),
  SOUND_MP3(2),
  SOUND_OGG(3),
  SOUND_UNKNOWN(4);

  public final int swigValue() {
    return swigValue;
  }

  public static USoundFormat swigToEnum(int swigValue) {
    USoundFormat[] swigValues = USoundFormat.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (USoundFormat swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + USoundFormat.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private USoundFormat() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private USoundFormat(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private USoundFormat(USoundFormat swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

