/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class USoundImpl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected USoundImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(USoundImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_USoundImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static USoundImpl make() {
    return new USoundImpl(urbiJNI.USoundImpl_make(), true);
  }

  public void init() {
    urbiJNI.USoundImpl_init(swigCPtr, this);
  }

  public String format_string() {
    return urbiJNI.USoundImpl_format_string(swigCPtr, this);
  }

  public boolean isEqual(USoundImpl b) {
    return urbiJNI.USoundImpl_isEqual(swigCPtr, this, USoundImpl.getCPtr(b), b);
  }

  public SWIGTYPE_p_std__ostream dump(SWIGTYPE_p_std__ostream o) {
    return new SWIGTYPE_p_std__ostream(urbiJNI.USoundImpl_dump(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(o)), false);
  }

  public void setSize(long value) {
    urbiJNI.USoundImpl_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return urbiJNI.USoundImpl_size_get(swigCPtr, this);
  }

  public void setChannels(long value) {
    urbiJNI.USoundImpl_channels_set(swigCPtr, this, value);
  }

  public long getChannels() {
    return urbiJNI.USoundImpl_channels_get(swigCPtr, this);
  }

  public void setRate(long value) {
    urbiJNI.USoundImpl_rate_set(swigCPtr, this, value);
  }

  public long getRate() {
    return urbiJNI.USoundImpl_rate_get(swigCPtr, this);
  }

  public void setSampleSize(long value) {
    urbiJNI.USoundImpl_sampleSize_set(swigCPtr, this, value);
  }

  public long getSampleSize() {
    return urbiJNI.USoundImpl_sampleSize_get(swigCPtr, this);
  }

  public void setSoundFormat(USoundFormat value) {
    urbiJNI.USoundImpl_soundFormat_set(swigCPtr, this, value.swigValue());
  }

  public USoundFormat getSoundFormat() {
    return USoundFormat.swigToEnum(urbiJNI.USoundImpl_soundFormat_get(swigCPtr, this));
  }

  public void setSampleFormat(USoundSampleFormat value) {
    urbiJNI.USoundImpl_sampleFormat_set(swigCPtr, this, value.swigValue());
  }

  public USoundSampleFormat getSampleFormat() {
    return USoundSampleFormat.swigToEnum(urbiJNI.USoundImpl_sampleFormat_get(swigCPtr, this));
  }

  public void setData(byte[] value) {
    urbiJNI.USoundImpl_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
  return urbiJNI.USoundImpl_data_get(swigCPtr, this);
}

  public void deleteData() {
    urbiJNI.USoundImpl_deleteData(swigCPtr, this);
  }

  public USoundImpl() {
    this(urbiJNI.new_USoundImpl(), true);
  }

}
