/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;
  /*---------.
  | USound.  |
  `---------*/
  /** Class encapsulating sound information.

   This class does not handle its memory: the data field must be
   freed manualy.  */

public class USound {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected USound(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(USound obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_USound(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

      /// Return an empty instance.
    /// Not a constructor so that we can still put it in a union.
 public  static USound make() {
    return new USound(urbiJNI.USound_make(), true);
  }

  public void init() {
    urbiJNI.USound_init(swigCPtr, this);
  }

      /// Return a legible definition of imageFormat.
 public  String format_string() {
    return urbiJNI.USound_format_string(swigCPtr, this);
  }

  public boolean isEqual(USound b) {
    return urbiJNI.USound_isEqual(swigCPtr, this, USound.getCPtr(b), b);
  }

  public void setSize(long value) {
    urbiJNI.USound_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return urbiJNI.USound_size_get(swigCPtr, this);
  }

  public void setChannels(long value) {
    urbiJNI.USound_channels_set(swigCPtr, this, value);
  }

  public long getChannels() {
    return urbiJNI.USound_channels_get(swigCPtr, this);
  }

  public void setRate(long value) {
    urbiJNI.USound_rate_set(swigCPtr, this, value);
  }

  public long getRate() {
    return urbiJNI.USound_rate_get(swigCPtr, this);
  }

  public void setSampleSize(long value) {
    urbiJNI.USound_sampleSize_set(swigCPtr, this, value);
  }

  public long getSampleSize() {
    return urbiJNI.USound_sampleSize_get(swigCPtr, this);
  }

  public void setSoundFormat(USoundFormat value) {
    urbiJNI.USound_soundFormat_set(swigCPtr, this, value.swigValue());
  }

  public USoundFormat getSoundFormat() {
    return USoundFormat.swigToEnum(urbiJNI.USound_soundFormat_get(swigCPtr, this));
  }

  public void setSampleFormat(USoundSampleFormat value) {
    urbiJNI.USound_sampleFormat_set(swigCPtr, this, value.swigValue());
  }

  public USoundSampleFormat getSampleFormat() {
    return USoundSampleFormat.swigToEnum(urbiJNI.USound_sampleFormat_get(swigCPtr, this));
  }

  public void setData(byte[] value) {
    urbiJNI.USound_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
  return urbiJNI.USound_data_get(swigCPtr, this);
}

  public void deleteData() {
    urbiJNI.USound_deleteData(swigCPtr, this);
  }

  public USound() {
    this(urbiJNI.new_USound(), true);
  }

}
