/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public enum UTransmitFormat {
  URBI_TRANSMIT_JPEG,
  URBI_TRANSMIT_YCbCr;

  public final int swigValue() {
    return swigValue;
  }

  public static UTransmitFormat swigToEnum(int swigValue) {
    UTransmitFormat[] swigValues = UTransmitFormat.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (UTransmitFormat swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + UTransmitFormat.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private UTransmitFormat() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private UTransmitFormat(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private UTransmitFormat(UTransmitFormat swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

