/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;
  /*---------.
  | UValue.  |
  `---------*/
  /** Container for a value that handles all types known to URBI.
   */

public class UValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(UDataType value) {
    urbiJNI.UValue_type_set(swigCPtr, this, value.swigValue());
  }

  public UDataType getType() {
    return UDataType.swigToEnum(urbiJNI.UValue_type_get(swigCPtr, this));
  }

  public void setVal(double value) {
    urbiJNI.UValue_val_set(swigCPtr, this, value);
  }

  public double getVal() {
    return urbiJNI.UValue_val_get(swigCPtr, this);
  }

  public UValue() {
    this(urbiJNI.new_UValue__SWIG_0(), true);
  }

  public UValue(UValue arg0) {
    this(urbiJNI.new_UValue__SWIG_1(UValue.getCPtr(arg0), arg0), true);
  }

  public UValue setValue(UValue arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_0(swigCPtr, this, UValue.getCPtr(arg0), arg0), false);
  }

      /// Setter. If copy is false, binary data if present is not copied.
    /// This is dangerous, as the user must ensure that the source UValue
    /// lives longer than this one.
 public  UValue setValue(UValue arg0, boolean copy) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_1(swigCPtr, this, UValue.getCPtr(arg0), arg0, copy), false);
  }

      /// Delete content and reset type to void.
 public  void clear() {
    urbiJNI.UValue_clear(swigCPtr, this);
  }

      /// A specific UValue used when we want to return an error.
    /// For instance, out-of-bound access returns this object.
 public  static UValue error() {
    return new UValue(urbiJNI.UValue_error(), false);
  }

      /// Return a legible definition of UDataType
 public  String format_string() {
    return urbiJNI.UValue_format_string(swigCPtr, this);
  }

  public UValue(double arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_2(arg0, copy), true);
  }

  public UValue(double arg0) {
    this(urbiJNI.new_UValue__SWIG_3(arg0), true);
  }

  public UValue setValue(double arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_2(swigCPtr, this, arg0), false);
  }

  public UValue(int arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_4(arg0, copy), true);
  }

  public UValue(int arg0) {
    this(urbiJNI.new_UValue__SWIG_5(arg0), true);
  }

  public UValue setValue(int arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_3(swigCPtr, this, arg0), false);
  }

  public UValue(long arg0) {
    this(urbiJNI.new_UValue__SWIG_7(arg0), true);
  }

  public UValue setValue(long arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_5(swigCPtr, this, arg0), false);
  }

  public UValue(java.math.BigInteger arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_9(arg0, copy), true);
  }

  public UValue(java.math.BigInteger arg0) {
    this(urbiJNI.new_UValue__SWIG_10(arg0), true);
  }

  public UValue setValue(java.math.BigInteger arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_7(swigCPtr, this, arg0), false);
  }

  public UValue(String arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_12(arg0, copy), true);
  }

  public UValue(String arg0) {
    this(urbiJNI.new_UValue__SWIG_13(arg0), true);
  }

  public UValue setValue(String arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_9(swigCPtr, this, arg0), false);
  }

  public UValue(UBinary arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_16(UBinary.getCPtr(arg0), arg0, copy), true);
  }

  public UValue(UBinary arg0) {
    this(urbiJNI.new_UValue__SWIG_17(UBinary.getCPtr(arg0), arg0), true);
  }

  public UValue setValue(UBinary arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_11(swigCPtr, this, UBinary.getCPtr(arg0), arg0), false);
  }

  public UValue(UList arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_18(UList.getCPtr(arg0), arg0, copy), true);
  }

  public UValue(UList arg0) {
    this(urbiJNI.new_UValue__SWIG_19(UList.getCPtr(arg0), arg0), true);
  }

  public UValue setValue(UList arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_12(swigCPtr, this, UList.getCPtr(arg0), arg0), false);
  }

  public UValue(UDictionary arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_20(UDictionary.getCPtr(arg0), arg0, copy), true);
  }

  public UValue(UDictionary arg0) {
    this(urbiJNI.new_UValue__SWIG_21(UDictionary.getCPtr(arg0), arg0), true);
  }

  public UValue setValue(UDictionary arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_13(swigCPtr, this, UDictionary.getCPtr(arg0), arg0), false);
  }

  public UValue(USound arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_22(USound.getCPtr(arg0), arg0, copy), true);
  }

  public UValue(USound arg0) {
    this(urbiJNI.new_UValue__SWIG_23(USound.getCPtr(arg0), arg0), true);
  }

  public UValue setValue(USound arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_14(swigCPtr, this, USound.getCPtr(arg0), arg0), false);
  }

  public UValue(UImage arg0, boolean copy) {
    this(urbiJNI.new_UValue__SWIG_24(UImage.getCPtr(arg0), arg0, copy), true);
  }

  public UValue(UImage arg0) {
    this(urbiJNI.new_UValue__SWIG_25(UImage.getCPtr(arg0), arg0), true);
  }

  public UValue setValue(UImage arg0) {
    return new UValue(urbiJNI.UValue_setValue__SWIG_15(swigCPtr, this, UImage.getCPtr(arg0), arg0), false);
  }

  public double doubleValue() {
    return urbiJNI.UValue_doubleValue__SWIG_0(swigCPtr, this);
  }

  public String stringValue() {
    return urbiJNI.UValue_stringValue(swigCPtr, this);
  }

  public int intValue() {
    return urbiJNI.UValue_intValue(swigCPtr, this);
  }

  public long longValue() {
    return urbiJNI.UValue_longValue(swigCPtr, this);
  }

  public boolean booleanValue() {
    return urbiJNI.UValue_booleanValue(swigCPtr, this);
  }

  public UBinary ubinaryValue() {
    return new UBinary(urbiJNI.UValue_ubinaryValue(swigCPtr, this), false);
  }

  public UList ulistValue() {
    return new UList(urbiJNI.UValue_ulistValue(swigCPtr, this), true);
  }

  public UDictionary udictionaryValue() {
    return new UDictionary(urbiJNI.UValue_udictionaryValue(swigCPtr, this), true);
  }

  public UImage uimageValue() {
    return new UImage(urbiJNI.UValue_uimageValue(swigCPtr, this), true);
  }

  public USound usoundValue() {
    return new USound(urbiJNI.UValue_usoundValue(swigCPtr, this), true);
  }

  public String toString() {
    return urbiJNI.UValue_toString(swigCPtr, this);
  }

}
