/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UValueVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UValueVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UValueVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UValueVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UValueVector() {
    this(urbiJNI.new_UValueVector__SWIG_0(), true);
  }

  public UValueVector(long n) {
    this(urbiJNI.new_UValueVector__SWIG_1(n), true);
  }

  public long size() {
    return urbiJNI.UValueVector_size(swigCPtr, this);
  }

  public long capacity() {
    return urbiJNI.UValueVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    urbiJNI.UValueVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return urbiJNI.UValueVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    urbiJNI.UValueVector_clear(swigCPtr, this);
  }

  public void add(UValue x) {
    urbiJNI.UValueVector_add(swigCPtr, this, UValue.getCPtr(x), x);
  }

  public UValue get(int i) {
    long cPtr = urbiJNI.UValueVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new UValue(cPtr, false);
  }

  public void set(int i, UValue val) {
    urbiJNI.UValueVector_set(swigCPtr, this, i, UValue.getCPtr(val), val);
  }

}
