/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UVarImpl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UVarImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UVarImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UVarImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void initialize(UVar owner) {
    urbiJNI.UVarImpl_initialize(swigCPtr, this, UVar.getCPtr(owner), owner);
  }

  public void clean() {
    urbiJNI.UVarImpl_clean(swigCPtr, this);
  }

  public void setOwned() {
    urbiJNI.UVarImpl_setOwned(swigCPtr, this);
  }

  public void sync() {
    urbiJNI.UVarImpl_sync(swigCPtr, this);
  }

  public void request() {
    urbiJNI.UVarImpl_request(swigCPtr, this);
  }

  public void keepSynchronized() {
    urbiJNI.UVarImpl_keepSynchronized(swigCPtr, this);
  }

        // Set the UVar value from v. Must deep-copy unless bypass mode is enabled
 public  void set(UValue v) {
    urbiJNI.UVarImpl_set(swigCPtr, this, UValue.getCPtr(v), v);
  }

  public UValue get() {
    return new UValue(urbiJNI.UVarImpl_get(swigCPtr, this), false);
  }

  public UDataType type() {
    return UDataType.swigToEnum(urbiJNI.UVarImpl_type(swigCPtr, this));
  }

  public UValue getProp(UProperty prop) {
    return new UValue(urbiJNI.UVarImpl_getProp(swigCPtr, this, prop.swigValue()), true);
  }

  public void setProp(UProperty prop, UValue v) {
    urbiJNI.UVarImpl_setProp(swigCPtr, this, prop.swigValue(), UValue.getCPtr(v), v);
  }

  public boolean setBypass(boolean enable) {
    return urbiJNI.UVarImpl_setBypass(swigCPtr, this, enable);
  }

  public void unnotify() {
    urbiJNI.UVarImpl_unnotify(swigCPtr, this);
  }

  public void useRTP(boolean enable) {
    urbiJNI.UVarImpl_useRTP(swigCPtr, this, enable);
  }

  public void setInputPort(boolean enable) {
    urbiJNI.UVarImpl_setInputPort(swigCPtr, this, enable);
  }

}
