/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package urbi;

public class UVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        urbiJNI.delete_UVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long size() {
    return urbiJNI.UVector_size(swigCPtr, this);
  }

  public double get(int i) {
    return urbiJNI.UVector_get(swigCPtr, this, i);
  }

  public void set(int i, double v) {
    urbiJNI.UVector_set(swigCPtr, this, i, v);
  }

  public UVector() {
    this(urbiJNI.new_UVector(), true);
  }

}
